### ISSUE TITLE
Can't get rake compile to run

### ISSUE THREAD

**Issue by rhyous** [heelhook/chardin.js#89]
Yes, it is my first time compiling with rake. 

What I did:
1. I installed Ruby. It installed rake version 10.5.0. 
   Note: However, the project requires rake. 10.0.4. 
2. I installed that. I installed all the dependencies. 
3. I ran this command: `rake compile`

Result:

```
C:\Users\jbarneck\Documents\Projects\GIT\chardinjs>rake compile --trace
rake aborted!
Gem::LoadError: You have already activated rake 10.5.0, but your Gemfile requires rake 10.0.4. Prepe
nding `bundle exec` to your command may solve this.
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:34:in `block in set
up'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:19:in `setup'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
C:/Users/jbarneck/Documents/Projects/GIT/chardinjs/Rakefile:3:in `<top (required)>'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'

D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rake
file'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_
rakefile'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exce
ption_handling'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'

D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exce
ption_handling'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
D:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
D:/dev/Ruby22-x64/bin/rake:23:in `load'
D:/dev/Ruby22-x64/bin/rake:23:in `<main>'
```

Can we get some updated steps for compiling?
##

**Comment by rhyous** [comment]
I just got compile to working by simply deleting the gem.lock file.

For this type of project, the gem.lock file should probably not be checked in.
http://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore
